'[\s\t\n]+': ''
'\/\/([^\n]+)': ''
'\;': ';'
'=': '='
'let': 'LET'
'if': 'IF'
'else': 'ELSE'
'print': 'PRINT'
'([a-zA-Z\_]+)': 'WORD'
'([0-9]+)': 'NUMBER'
'\"(.*)\"': 'STRING'
'(\+|\-|\*\/)': 'MATH_OPERATOR'
'\(': '('
'\)': ')'
'\{': '{'
'\}': '}'
'\>': '>'
'\<': '<'